# Generated by Django 3.2.3 on 2021-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16)),
                ('user_email', models.CharField(max_length=60)),
                ('user_password', models.CharField(max_length=256)),
                ('user_introduction', models.TextField(max_length=600)),
                ('user_create_date', models.DateField(auto_now_add=True)),
                ('user_point', models.IntegerField(default=0)),
            ],
        ),
    ]
